language: rust

cache: cargo

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

git:
  depth: 10

before_script:
  - chmod +x benches-compare.sh

script:
  - cargo build --v